In [1]:
import pandas as pd

# Read JSON files
listings_df = pd.read_json("C:/Users/mchar/OneDrive/Documents/Guvi/Project 1-Brick-View/listings_final_expanded.json")
property_df = pd.read_json("C:/Users/mchar/OneDrive/Documents/Guvi/Project 1-Brick-View/property_attributes_final_expanded.json")
agents_df = pd.read_json("C:/Users/mchar/OneDrive/Documents/Guvi/Project 1-Brick-View/agents_cleaned.json")
buyers_df = pd.read_json("C:/Users/mchar/OneDrive/Documents/Guvi/Project 1-Brick-View/buyers_cleaned.json")
sales_df = pd.read_csv("C:/Users/mchar/OneDrive/Documents/Guvi/Project 1-Brick-View/sales_cleaned.csv")
# Quick check
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [ ]:
# 2 FILTER AND EXPLORE 
elif page == "Filter and Explore":
    st.title("🔴 Filters & Property Explorer")
    query = "SELECT * FROM listings"
    df = pd.read_sql(query, connection)
    col1, col2, col3 = st.columns(3)
    with col1:
        city = st.selectbox("City", ["All"] + sorted(df["City"].dropna().unique().tolist()))
    with col2:
        property_type = st.selectbox("Property Type",["All"] + sorted(df["Property_Type"].dropna().unique().tolist()))
    with col3:
        min_price = int(df["Price"].min())
        max_price = int(df["Price"].max())

        price_range = st.slider(
            "Price Range ($)",
            min_price,
            max_price,
            (min_price, max_price))

In [2]:
#quick summary of your dataset.
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  object
 1   City           21200 non-null  object
 2   Property_Type  21200 non-null  object
 3   Price          21200 non-null  float64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  object
 6   Agent_ID       21200 non-null  object
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.5+ MB

In [56]:
# Step 3: Fix Price column (remove scientific notation)
listings_df['Price'] = listings_df['Price'].astype(float).round(0).astype(int)
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162489,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277016,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [57]:
# Convert date
listings_df['Date_Listed'] = pd.to_datetime(listings_df['Date_Listed'])
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162489,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277016,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [58]:
# Check data
print(listings_df.columns)

Index(['Listing_ID', 'City', 'Property_Type', 'Price', 'Sqft', 'Date_Listed',
       'Agent_ID', 'Latitude', 'Longitude'],
      dtype='object')

In [59]:
# Check Null Value
listings_df.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [2]:
# Read JSON files
property_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [61]:
#quick summary of your dataset.
property_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

In [62]:
print(property_df.columns)

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [7]:
# Check data
print(property_df.columns)

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [63]:
# Read JSON files
agents_df.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [64]:
#quick summary of your dataset.
agents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agent_ID          50 non-null     object
 1   Name              50 non-null     object
 2   Phone             50 non-null     object
 3   Email             50 non-null     object
 4   commission_rate   50 non-null     float64
 5   deals_closed      50 non-null     int64
 6   rating            50 non-null     float64
 7   experience_years  50 non-null     int64
 8   avg_closing_days  50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

In [65]:
# Read JSON files
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [66]:
#quick summary of your dataset.
buyers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   buyer_id       20000 non-null  int64
 1   sale_id        20000 non-null  object
 2   buyer_type     20000 non-null  object
 3   payment_mode   20000 non-null  object
 4   loan_taken     20000 non-null  bool
 5   loan_provider  10034 non-null  object
 6   loan_amount    20000 non-null  int64
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

In [67]:
# Read JSON files
sales_df.head()

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [11]:
# Step 3: Fix Price column (remove scientific notation)
sales_df['Sale_Price'] = sales_df['Sale_Price'].astype(float).round(0).astype(int)
sales_df.head()

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07       65.005560
1     L00866      105416  2023-06-14       38.004620
2     L00102     1825184  2023-09-09       22.992622
3     L00440     1932085  2023-10-29       72.012274
4     L00059      776586  2023-05-01      116.000152

In [12]:
#  Fix Days_on_Market
sales_df['Days_on_Market'] = sales_df['Days_on_Market'].astype(float).round(0).astype(int)
sales_df.head()

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07              65
1     L00866      105416  2023-06-14              38
2     L00102     1825184  2023-09-09              23
3     L00440     1932085  2023-10-29              72
4     L00059      776586  2023-05-01             116

In [13]:
#quick summary of your dataset.
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_ID      720 non-null    object
 1   Sale_Price      720 non-null    int64
 2   Date_Sold       720 non-null    object
 3   Days_on_Market  720 non-null    int64
dtypes: int64(2), object(2)
memory usage: 22.6+ KB

In [27]:
#Installing Library
!pip install pymysql mysql-connector-python

Requirement already satisfied: pymysql in c:\users\mchar\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: mysql-connector-python in c:\users\mchar\anaconda3\lib\site-packages (9.6.0)

In [71]:
# Connecting to mysql database
import mysql.connector
from mysql.connector import Error
# Setting up connection
connection = mysql.connector.connect(
    host ='127.0.0.1',
    user = 'root',
    password = 'Mayuri1997',
    database= 'BrickView'
)
if connection.is_connected():
    print('connection to MySQL database is Successful.')

connection to MySQL database is Successful.

In [68]:
#Getting the data from mysql database

cursor = connection.cursor()
cursor.execute("Create Database if not exists BrickView")
connection.commit()

In [23]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Mayuri1997@localhost/Brickview")

print("Connected to MySQL")

Connected to MySQL

In [24]:
agents_df.to_sql('agents', engine, if_exists='replace', index=False)
buyers_df.to_sql('buyers', engine, if_exists='replace', index=False)
property_df.to_sql('property', engine, if_exists='replace', index=False)
sales_df.to_sql('sales', engine, if_exists='replace', index=False)

print("Data uploaded successfully!")

Data uploaded successfully!

In [18]:
listings_df.to_sql('listings', engine, if_exists='replace', index=False)

21200

In [ ]:
''''Property & Pricing Analysis''''

In [37]:
#1-What is the average listing price by city?
query = """
SELECT 
    City,
    ROUND(AVG(price), 2) AS avg_listing_price
FROM listings
WHERE price IS NOT NULL
GROUP BY City
ORDER BY avg_listing_price DESC;
"""

# Execute query
result_df = pd.read_sql(query, engine)

# Show output
result_df.head()

          City  avg_listing_price
0     New York         2493319.74
1      Phoenix         2459961.76
2  Los Angeles         2442418.32
3      Houston         2436811.00
4      Chicago         2430677.90

In [42]:
#2-What is the average price per square foot by property type?
query = """
SELECT 
    property_type,
    ROUND(AVG(price / sqft), 2) AS avg_price_per_sqft
FROM listings
WHERE price IS NOT NULL 
  AND sqft IS NOT NULL
  AND sqft > 0
GROUP BY property_type
ORDER BY avg_price_per_sqft DESC;
"""

result_df = pd.read_sql(query, engine)

result_df.head()

  property_type  avg_price_per_sqft
0         House              796.04
1     Apartment              792.20
2     Townhouse              789.75
3         Condo              754.68

In [56]:
#3-How does furnishing status impact property prices?
query = """
SELECT 
    property.furnishing_status,
    AVG(listings.Price) AS avg_price
FROM listings
JOIN property
    ON listings.Listing_ID = property.listing_id
GROUP BY property.furnishing_status;
"""

result_df = pd.read_sql(query, engine)

result_df.head()

  furnishing_status     avg_price
0         Furnished  2.463539e+06
1       Unfurnished  2.433975e+06
2    Semi-Furnished  2.461193e+06

In [57]:
#4-Do properties closer to metro stations command higher prices?

query = """
SELECT 
    CASE 
        WHEN property.metro_distance_km <= 1 THEN 'Near Metro'
        ELSE 'Far from Metro'
    END AS near_metro,
    AVG(listings.Price) AS avg_price
FROM listings
JOIN property
    ON listings.Listing_ID = property.listing_id
GROUP BY 
    CASE 
        WHEN property.metro_distance_km <= 1 THEN 'Near Metro'
        ELSE 'Far from Metro'
    END;
    """

result_df = pd.read_sql(query, engine)

result_df.head()

       near_metro     avg_price
0  Far from Metro  2.457369e+06
1      Near Metro  2.386849e+06

In [58]:
#5-Are rented properties priced differently from non-rented ones?
query = """
SELECT 
    CASE 
        WHEN property.is_rented = 1 THEN 'Rented'
        ELSE 'Not Rented'
    END AS rental_status,
    AVG(listings.Price) AS avg_price
FROM listings
JOIN property
    ON listings.Listing_ID = property.listing_id
GROUP BY property.is_rented;
"""
result_df = pd.read_sql(query, engine)

result_df.head()

  rental_status     avg_price
0        Rented  2.457185e+06
1    Not Rented  2.448250e+06

In [60]:
#6-How do bedrooms and bathrooms affect pricing?
query = """
SELECT 
    property.bedrooms,
    property.bathrooms,
    AVG(listings.Price) AS avg_price
FROM listings
JOIN property
    ON listings.Listing_ID = property.listing_id
GROUP BY property.bedrooms, property.bathrooms;
"""
result_df = pd.read_sql(query,engine)
result_df.head()

   bedrooms  bathrooms     avg_price
0         5          3  2.424067e+06
1         2          2  2.378688e+06
2         2          3  2.482619e+06
3         3          3  2.455024e+06
4         1          3  2.459033e+06

In [61]:
#7-Do properties with parking and power backup sell at higher prices?
query = """
SELECT 
    property.parking_available,
    property.power_backup,
    AVG(listings.Price) AS avg_price
FROM listings
JOIN property
    ON listings.Listing_ID = property.listing_id
GROUP BY property.parking_available, property.power_backup;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

   parking_available  power_backup     avg_price
0                  0             1  2.446293e+06
1                  1             0  2.462364e+06
2                  0             0  2.436678e+06
3                  1             1  2.465652e+06

In [62]:
#8- How does year built influence listing price?
query = """
SELECT 
    property.year_built,
    AVG(listings.Price) AS avg_price
FROM listings
JOIN property
    ON listings.Listing_ID = property.listing_id
GROUP BY property.year_built;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

   year_built     avg_price
0        2001  2.438764e+06
1        2020  2.465414e+06
2        2007  2.379429e+06
3        2003  2.395755e+06
4        2008  2.471225e+06

In [63]:
#9-Which cities have the highest average property prices?
query = """
SELECT 
    listings.City,
    AVG(listings.Price) AS avg_price
FROM listings
GROUP BY listings.City
ORDER BY avg_price DESC;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

          City     avg_price
0     New York  2.493320e+06
1      Phoenix  2.459962e+06
2  Los Angeles  2.442418e+06
3      Houston  2.436811e+06
4      Chicago  2.430678e+06

In [64]:
#10- How are properties distributed across price buckets?
query = """
SELECT 
    CASE 
        WHEN listings.Price <= 3000000 THEN '0-30L'
        WHEN listings.Price <= 5000000 THEN '30L-50L'
        WHEN listings.Price <= 7000000 THEN '50L-70L'
        WHEN listings.Price <= 9000000 THEN '70L-90L'
        ELSE '90L+'
    END AS price_range,
    COUNT(*) AS property_count
FROM listings
GROUP BY 
    CASE 
        WHEN listings.Price <= 3000000 THEN '0-30L'
        WHEN listings.Price <= 5000000 THEN '30L-50L'
        WHEN listings.Price <= 7000000 THEN '50L-70L'
        WHEN listings.Price <= 9000000 THEN '70L-90L'
        ELSE '90L+'
    END
ORDER BY price_range;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  price_range  property_count
0       0-30L           13094
1     30L-50L            8106

In [ ]:
''''⏱️ Sales & Market Performance''''

In [65]:
#11-What is the average days on market by city?
query = """
SELECT 
    listings.City,
    AVG(sales.Days_on_Market) AS avg_days_on_market
FROM sales
JOIN listings
    ON sales.Listing_ID = listings.Listing_ID
GROUP BY listings.City;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

          City  avg_days_on_market
0     New York             60.8467
1      Houston             58.5115
2      Phoenix             59.6548
3  Los Angeles             65.1250
4      Chicago             64.2500

In [68]:
#12-Which property types sell the fastest?
query = """
SELECT
listings.property_Type,
AVG(sales.Days_on_Market) AS avg_days_on_market
FROM Sales
JOIN Listings
ON Sales.Listing_ID = listings.Listing_ID
GROUP BY listings.Property_Type
ORDER BY avg_days_on_market ASC;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  property_Type  avg_days_on_market
0         House             58.3368
1     Apartment             60.6477
2     Townhouse             60.9641
3         Condo             66.5401

In [69]:
#13-What percentage of properties are sold above listing price?
query = """
SELECT 
(SUM(CASE 
WHEN sales.Sale_Price > listings.Price THEN 1 
ELSE 0 
 END) * 100.0) / COUNT(*) AS percentage_higher_than_list_price
FROM sales
JOIN listings
ON sales.Listing_ID = listings.Listing_ID;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

   percentage_higher_than_list_price
0                           49.30556

In [70]:
#14-What is the sale-to-list price ratio by city?
query = """
SELECT 
listings.City,
AVG(sales.Sale_Price / listings.Price) * 100 AS avg_price_ratio_percentage
FROM sales
JOIN listings
ON sales.Listing_ID = listings.Listing_ID
GROUP BY listings.City;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

          City  avg_price_ratio_percentage
0     New York                   99.958540
1      Houston                  100.000382
2      Phoenix                   99.890476
3  Los Angeles                   99.983672
4      Chicago                  100.152436

In [71]:
#15-What is the sale-to-list price ratio by city?
query = """
SELECT 
    listings.City,
    (AVG(CASE 
        WHEN sales.Days_on_Market > 90 THEN 1 
        ELSE 0 
    END) * 100) AS percentage_above_90_days
FROM sales
JOIN listings
    ON sales.Listing_ID = listings.Listing_ID
GROUP BY listings.City;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

          City  percentage_above_90_days
0     New York                   32.1168
1      Houston                   20.6107
2      Phoenix                   21.4286
3  Los Angeles                   32.8125
4      Chicago                   25.0000

In [72]:
#16-Which listings took more than 90 days to sell?
query = """
SELECT *
FROM sales
JOIN listings
    ON sales.Listing_ID = listings.Listing_ID
WHERE sales.Days_on_Market > 90;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

,Listing_ID,Sale_Price,Date_Sold,Days_on_Market,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00004,1215041,2024-04-27,116,L00004,Phoenix,Apartment,1277016,2128.014429,2024-01-02,A0042,26.403938,-74.771490
1,L00007,1625945,2023-06-10,108,L00007,Los Angeles,House,1701163,3257.015062,2023-02-22,A0006,44.969112,-112.678494
2,L00024,1309511,2023-10-16,91,L00024,Los Angeles,Townhouse,1350760,1019.987205,2023-07-17,A0025,32.475381,-94.832924
3,L00028,1101007,2023-12-18,92,L00028,New York,Condo,1149805,1963.008616,2023-09-17,A0007,39.343374,-71.523210
4,L00031,1917126,2023-08-19,108,L00031,New York,Condo,1942813,3018.992756,2023-05-03,A0004,34.326842,-109.248152

In [73]:
#17-How does metro distance affect time on market?
query = """
SELECT 
    property.metro_distance_km,
    AVG(sales.Days_on_Market) AS avg_days_on_market
FROM property
JOIN sales
    ON property.listing_id = sales.Listing_ID
GROUP BY property.metro_distance_km;

"""
result_df = pd.read_sql(query, engine)
result_df.head()

   metro_distance_km  avg_days_on_market
0               7.26             24.0000
1               4.92             47.5000
2               1.20             63.0000
3               7.25             53.2500
4               7.69             50.3333

In [22]:
#18-What is the monthly sales trend?
query = """
SELECT 
    DATE_FORMAT(sales.Date_Sold, '%%Y-%%m') AS month,
    COUNT(*) AS total_sales
FROM sales
GROUP BY DATE_FORMAT(sales.Date_Sold, '%%Y-%%m')
ORDER BY month;
"""

result_df = pd.read_sql(query, engine)
result_df.head()

     month  total_sales
0  2023-01            7
1  2023-02           17
2  2023-03           20
3  2023-04           36
4  2023-05           45

In [21]:
#19-Which properties are currently unsold?
query = """
SELECT *
FROM listings
WHERE Listing_ID NOT IN (
    SELECT Listing_ID
    FROM sales
)
"""
result_df = pd.read_sql(query, engine)
result_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
1,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878
2,L00009,New York,Townhouse,1224551,1522.007780,2024-05-13,A0025,32.302569,-94.556982
3,L00014,Chicago,Apartment,1377440,1900.998129,2023-10-01,A0047,29.772677,-95.162779
4,L00015,Los Angeles,House,1069429,3607.995839,2023-05-19,A0041,39.214998,-122.295145

In [30]:
#20-Which agents have closed the most sales?
query = """
SELECT 
    a.Name,
    COUNT(*) AS total_properties
FROM listings l
JOIN agents a
ON l.Agent_ID = a.Agent_ID
GROUP BY a.Name
ORDER BY total_properties DESC
"""

result_df = pd.read_sql(query, engine)
result_df.head()

          Name  total_properties
0  Agent A0011               463
1  Agent A0042               460
2  Agent A0023               458
3  Agent A0014               453
4  Agent A0008               449

In [32]:
#21-Who are the top agents by total sales revenue?
query = """
SELECT 
    a.Name,
    SUM(l.Price) AS Total_Price
FROM listings l
JOIN agents a
ON l.Agent_ID = a.Agent_ID
GROUP BY a.Name
ORDER BY Total_Price DESC;
"""

result_df = pd.read_sql(query, engine)
result_df.head()

          Name   Total_Price
0  Agent A0048  1.151917e+09
1  Agent A0042  1.115069e+09
2  Agent A0008  1.114257e+09
3  Agent A0011  1.104459e+09
4  Agent A0044  1.101312e+09

In [43]:
#22-Which agents close deals fastest?
query = """
SELECT 
    a.Name,
    AVG(s.Days_on_Market) AS Avg_Days_On_Market
FROM sales s
JOIN listings l
ON s.Listing_ID = l.Listing_ID
JOIN agents a
ON l.Agent_ID = a.Agent_ID
GROUP BY a.Name
ORDER BY Avg_Days_On_Market;
"""

result_df = pd.read_sql(query, engine)
result_df.head()

          Name  Avg_Days_On_Market
0  Agent A0044             36.8750
1  Agent A0013             42.4286
2  Agent A0037             44.5000
3  Agent A0002             45.5000
4  Agent A0008             46.6364

In [78]:
#23-Does experience correlate with deals closed?
query = """
SELECT 
agents.experience_years,
deals_closed
FROM agents
ORDER BY experience_years DESC;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

   experience_years  deals_closed
0                25            48
1                25            99
2                23           270
3                23            60
4                22            98

In [45]:
#24-Do agents with higher ratings close deals faster?
query = """
SELECT 
    agents.Agent_ID,
    agents.rating,
    AVG(sales.Days_on_Market) AS Avg_Days_On_Market
FROM sales
JOIN listings
ON sales.Listing_ID = listings.Listing_ID
JOIN agents
ON listings.Agent_ID = agents.Agent_ID
GROUP BY agents.Agent_ID, agents.rating;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  Agent_ID  rating  Avg_Days_On_Market
0    A0025     3.2             70.7647
1    A0007     3.8             64.4737
2    A0009     4.4             52.7059
3    A0028     4.0             55.6000
4    A0004     4.5             80.0909

In [80]:
#25 - What is the average commission earned by each agent?
query = """
SELECT 
    Agent_ID,commission_rate
FROM agents;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  Agent_ID  commission_rate
0    A0001             2.00
1    A0002             2.20
2    A0003             2.85
3    A0004             1.67
4    A0005             1.11

In [81]:
#26-Which agents currently have the most active listings?
query = """
SELECT 
Agent_ID,
    COUNT(*) AS total_listings
FROM listings
GROUP BY Agent_ID;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  Agent_ID  total_listings
0    A0015             441
1    A0038             413
2    A0042             460
3    A0018             435
4    A0006             418

In [48]:
#27-What percentage of buyers are investors vs end users?
query = """
SELECT 
    buyer_type,
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM buyers) AS Percentage
FROM buyers
GROUP BY buyer_type;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  buyer_type  Percentage
0   End User        50.1
1   Investor        49.9

In [49]:
#28-Which cities have the highest loan uptake rate?
query = """
SELECT 
    listings.City,
    AVG(buyers.loan_taken) * 100 AS Loan_Uptake_Percentage
FROM buyers
JOIN listings
ON buyers.sale_id = listings.Listing_ID
GROUP BY listings.City
ORDER BY Loan_Uptake_Percentage DESC;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

          City  Loan_Uptake_Percentage
0  Los Angeles                 50.9854
1      Chicago                 50.5662
2     New York                 50.2232
3      Houston                 49.7115
4      Phoenix                 49.4971

In [50]:
#29-What is the average loan amount by buyer type?

query = """
SELECT 
    buyer_type,
    AVG(loan_amount) AS Avg_Loan_Amount
FROM buyers
GROUP BY buyer_type;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

  buyer_type  Avg_Loan_Amount
0   End User     2.599434e+06
1   Investor     2.629272e+06

In [51]:
#30-Which payment mode is most commonly used?
query = """
SELECT 
    payment_mode,
    COUNT(*) AS Count
FROM buyers
GROUP BY payment_mode
ORDER BY Count DESC;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

    payment_mode  Count
0           Cash   5088
1            UPI   5012
2         Cheque   4951
3  Bank Transfer   4949

In [ ]:
#31-Do loan-backed purchases take longer to close?
query = """
SELECT 
    buyers.loan_taken,
    AVG(sales.Days_on_Market) AS Avg_Days_On_Market
FROM buyers
JOIN sales
ON buyers.sale_id = sales.Listing_ID
GROUP BY buyers.loan_taken;
"""
result_df = pd.read_sql(query, engine)
result_df.head()

In [82]:
%%writefile app.py
import streamlit as st

st.title("My Dashboard")
st.write("Real-time stats coming here")

x = st.slider("Pick a number", 0, 100)
st.write("You picked", x)

Overwriting app.py

In [ ]:
!streamlit run app.py

In [ ]:
import streamlit as st

In [ ]:
st.title("this is my project")